### ISSUE TITLE
Ruby Sass is deprecated

### ISSUE THREAD

**Issue by apjanke** [fieldtrip/website#104]
When installing the gems for a local run of the website:

```
[~/local/repos/fieldtrip-website]
$ bundle update --bundler
[...]

Post-install message from sass:

Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
[~/local/repos/fieldtrip-website]
$ bundle install
[...]
Using sass 3.7.2
[...]
```

Looks like this is being pulled in by the website's gem dependencies:

```
[~/local/repos/fieldtrip-website]
$ grep -r sass *
Gemfile.lock:      jekyll-sass-converter (~> 1.0)
Gemfile.lock:    jekyll-sass-converter (1.5.2)
Gemfile.lock:      sass (~> 3.4)
Gemfile.lock:    sass (3.7.2)
Gemfile.lock:      sass-listen (~> 4.0.0)
Gemfile.lock:    sass-listen (4.0.0)
_config.yml:sass:
_config.yml:  sass_dir: ./assets/css
assets/css/bootstrap/_root.scss:  // See https://github.com/sass/sass/issues/2383#issuecomment-336349172
```

Should something be done to switch to the `sassc` gem?

**Comment by robertoostenveld** [comment]
I started with a default Jekyll installation following http://jekyllrb.com/ and don't  really know what `sass` is, it was installed as dependency.  

Feel free to suggest an update to the Gemfile in a PR, @Spaak and I can then check whether it also works for us (on our respective desktops and on the web server).

**Comment by apjanke** [comment]
Per [Jekyll upstream](https://github.com/jekyll/jekyll-sass-converter/issues/74#issuecomment-483991957):

> The version to support sassc over sass will be a 2.0.0. Jekyll 3.8 and older will not be making the switch.
Instead only Jekyll 4.0 and beyond will be able to use jekyll-sass-converter-2.0.0 out-of-the-box.

So the thing to do here is just ignore the message and wait until Jekyll 4.0 comes out.

Closing as nothing-to-do.

**Comment by robertoostenveld** [comment]
thanks. I will still have to learn how to maintain the website on the longer run. Right now I am already happy that as of recently - using http://github.com/Donders-Institute/hpc-webhook/ - I can have the website automatically rebuilt within a few minutes after an update.
