### ISSUE TITLE
Missing Illustrator swatch in guideline/documentation

### ISSUE THREAD

**Issue by apjanke** [fieldtrip/website#105]
http://www.fieldtriptoolbox.org/development/guideline/documentation/ says:

> Here you can download Adobe Illustrator swatch (palette) and an example.

But there's no link to an actual swatch file.

**Comment by robertoostenveld** [comment]
This was originally an idea of @stephenwhitmarsh, but we never managed to settle on a consistent color scheme. Also SVG did not really work, so now most figures are in PNG. I will remove it from the documentation.
