### ISSUE TITLE
prepare the tutorials for oslo2019 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#132]
Tagging @ualsbombe and @britta-wstnr who will also be working on this.

**Comment by ualsbombe** [comment]
Created the .m-files in the tutorial for each of the five tutorials: (oslo2019/tutorials)
1_introduction_to_FieldTrip_and_EEG.m
2_frequency_and_time_frequency_analysis.m
3_statistics.m
4_source_reconstruction.m
5_forward_model_computation.m

**Comment by robertoostenveld** [comment]
I have created a `0_convert_data.m` script in the shared dropbox, and converted the original fif data to a brainvision triplet for the EEG and a triplet for the AUX (with the bipolar channels). I think that makes it easier to explain that the data has different references. You can use the same ft_preprocessing on both (the events are exactly the same on both datasets) and then append (if you want) with ft_appenddata.

If you both agree, please move the datafiles out of the shared dropbox and keep them somewhere else (to keep the dropbox small, also for the others we are sharing with).

We might want to document the `0_convert_data.m` script on the website as well (for reference). That is also what we did [here](http://www.fieldtriptoolbox.org/workshop/madrid2019/#the-data-used-for-the-hands-on-sessions) with [this conversion script](http://www.fieldtriptoolbox.org/workshop/madrid2019/convert_bids/).

**Comment by robertoostenveld** [comment]
I have added it to the FTP server, the converted data will appear (in an hour or so) on ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/workshop/oslo2019/

**Comment by ualsbombe** [comment]
Great, I'll remove it from the dropbox as soon as it has been correctly uploaded.

**Comment by ualsbombe** [comment]
@britta-wstnr, now a folder for adding images has been added in: /assets/img/workshop/oslo2019

**Comment by ualsbombe** [comment]
By the way, the information about electrode positions seems to be lost in the conversion from fif to the brainvision triplet? _ft\_read\_sens_ does not work on any of the files at least...

**Comment by robertoostenveld** [comment]
Please try the mat file. The brainvision files do not contain positions.

Verstuurd vanaf mijn iPhone

**Comment by ualsbombe** [comment]
There is no .mat file in the ftp. Only: .eeg, .vhdr and .vmrk
Might you have them somewhere else?

**Comment by robertoostenveld** [comment]
I just merged #140, which includes multiple PNGs and the introduction tutorial. I still see multiple issues with it, e.g. the first numbered list is glued together with the next paragraph, and an image is missing or incorrectly named. Please check it out on http://www.fieldtriptoolbox.org/workshop/oslo2019/introduction/

**Comment by robertoostenveld** [comment]
also the table-of-content reveals that the structure (heading levels) is not right yet. See http://www.fieldtriptoolbox.org/development/guideline/documentation/#how-to-structure-a-tutorial.

Furthermore, I find the layout quite crappy. The channel boxes are too large. 
![multiplot](https://user-images.githubusercontent.com/899043/58312172-08452500-7e0b-11e9-84a8-3b6522e88eba.png)

If I reduce the width and height with 50%, I get this

![Screen Shot 2019-05-24 at 09 24 15](https://user-images.githubusercontent.com/899043/58312204-17c46e00-7e0b-11e9-8db4-5b43462fde32.png)

Shall I update the `natmeg_customized_eeg1005.lay` in fieldtrip/template/layout?

**Comment by robertoostenveld** [comment]
> There is no .mat file in the ftp. Only: .eeg, .vhdr and .vmrk
> Might you have them somewhere else?

It was created in the `0_convert_data.m` script, but apparently not copied over from Dropbox to ftp. I have just added it to both the ftp _and_ Dropbox.  The ftp always takes some time to update.

**Comment by ualsbombe** [comment]
Thanks, Robert - that sounds good - updating the layout would be great, thanks!

**Comment by robertoostenveld** [comment]
I have just updated the layout 

mac011> git push upstream master
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 2.20 KiB | 2.20 MiB/s, done.
Total 7 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:fieldtrip/fieldtrip.git
   aa200a68d..a288d4144  master -> master

**Comment by robertoostenveld** [comment]
it is still up for improvements, since there is quite a large rim around the outer electrodes and the circle. Topoplot interpolations will look ugly like this.

**Comment by britta-wstnr** [comment]
For completeness, the PR for the **Time frequency tutorial** is in #145

**Comment by robertoostenveld** [comment]
is there still work to be done on the tutorials? If not, please feel free to close this issue.

**Comment by ualsbombe** [comment]
Since you opened it, I cannot close it, but please feel free to do so (seen from side)
