### ISSUE TITLE
Compatible with TRENTOOL

### ISSUE THREAD

**Issue by aliekhlasi** [fieldtrip/website#180]
Hello
Which one of fieldtrip versions compatible with trentool to calculate transfer entropy in time series?
I have full of error in fieldtrip functions

like these:

Error in getdimord>warning_dimord_could_not_be_determined (line 665)
    newline_pos=find(full_content==newline);

Error in getdimord (line 631)
  warning_dimord_could_not_be_determined(field, data);

Error in makessense (line 40)
    dimord = getdimord(data, datfield{i});

Error in ft_datatype_raw (line 89)
  hassampleinfo = makessense(data, 'sampleinfo');

Error in ft_checkdata (line 268)
  data = ft_datatype_raw(data, 'hassampleinfo', hassampleinfo);

thanks for your attention

**Comment by robertoostenveld** [comment]
This is not the place to ask support questions. Please see http://www.fieldtriptoolbox.org/discussion_list/ or ask the Trentool developers.
