### ISSUE TITLE
advertise the results from the paris workshop 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#189]
Add a news item about the Paris workshop and link to the new tutorials.

It would be good if @elshafeh would subsequently also tweet about it ;-)

**Comment by elshafeh** [comment]
@robertoostenveld oh sure! can u maybe send me the log-in / password? and i'll tweet it ;)

**Comment by elshafeh** [comment]
or maybe we wanna make a separate account for the "news"?
