### ISSUE TITLE
upgrade the tutorial on event-related averaging

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/website#196]
This tutorial is slightly outdated, especially the starting point (preprocessing of the data) should be revised. This is copied from a seperate tutorial, and should therefore also be revised there. Especially, data of all conditions should be read in at once and later seperated based on information stored in trialinfo.
Given the changes in preprocessing of the data, all data, code and figures should be updated. Additionally, the default colormap in figures should be changed to 'parula' (matlab default) and the layout for topoplots should be changed to the helmet version.

**Comment by robertoostenveld** [comment]
If there is "shared" text+figures between tutorials, we could see whether de-duplication can be improved. That is already done for some content, but it is not 100% consistent (for historical reasons). See e.g. https://github.com/fieldtrip/website/tree/master/_includes/shared/tutorial and search for `/shared/tutorial/preprocessing_fc_lp` in the MD files.

**Comment by robertoostenveld** [comment]
it would be good, also for @aranas and @yingjoeyzhou, to check each tutorial on whether it currently includes a shared section (or not). The shared sections are a bit more difficult to update, since in that case the downstream figures in multiple tutorials need to be updated.

For reference, these have shared sections in them:

```
mac036> grep -l include.*shared *.md
beamformer.md
cluster_permutation_freq.md
cluster_permutation_timelock.md
connectivity.md
connectivityextended.md
eventrelatedaveraging.md
hcp_motort.md
headmodel_eeg_bem.md
headmodel_eeg_fem.md
headmodel_meg.md
human_ecog.md
meg_language.md
minimumnormestimate.md
mmfaces.md
preprocessing.md
timefrequencyanalysis.md
virtual_sensors.md
```

**Comment by matsvanes** [comment]
Considering these shared parts of the tutorials, it is unclear how to proceed in preprocessing all conditions at once. It is not a problem to do so in the eventrelatedaveraging tutorial, because all conditions are used here, but most other tutorials that currently share text/figures only work on one of the conditions. I suggest to preprocess the full data for each of these (step 1), and if only one condition is required, select this condition and proceed (step 2).

**Comment by aranas** [comment]
@robertoostenveld  clarification question about your comment of whether "de-duplication can be improved", this means we want to try and have as much code as possible shared between tutorials?

@matsvanes what you suggests makes sense to me. Does this mean all five /shared/tutorial/preprocessing_* scripts will be reduced to one, containing step1 and we will then add the appropriate condition selection (step 2) to the tutorials? It seems that the hard-coded trial removal for artifact cleaning varies between the five shared scripts, do you know what that is about?

**Comment by aranas** [comment]
Right now there are several shared code file pertaining to the preprocessing:
**preprocessing_fic.md**
 (shared in) 
- tutorial/beamformer.md
- tutorial/cluster_permutation_freq.md
- tutorial/timefrequencyanalysis.md

**preprocessing_fic_lp**, **preprocessing_fc_lp** & **preprocessing_ic_lp**
- tutorial/cluster_permutation_timelock.md
- tutorial/eventrelatedaveraging.md
- tutorial/minimumnormestimate.md

I suggest to instead create the following shared files:
**definetrial_all.md**
(used by)
- tutorial/cluster_permutation_timelock.md
- tutorial/cluster_permutation_freq.md
- tutorial/eventrelatedaveraging.md
- tutorial/minimumnormestimate.md
- tutorial/beamformer.md
- tutorial/timefrequencyanalysis.md

**preprocessing_lp**
- tutorial/cluster_permutation_timelock.md
- tutorial/eventrelatedaveraging.md
- tutorial/minimumnormestimate.md

**preprocessing_nofilter**
- tutorial/beamformer.md
- tutorial/cluster_permutation_freq.md
- tutorial/timefrequencyanalysis.md

This will reduce the amount of shared files from 4 to 3, plus it would get rid of the repetitions of ft_definetrial code 

@matsvanes 
@yingjoeyzhou

**Comment by matsvanes** [comment]
I think that's a great idea @aranas! I think it will improve the consistency over tutorials and in the approach (start with all conditions). I don't think it will cause any major problems for the .mat files, they would only be a few we'd have to replace I think.

**definetrial_all.md** should also be used in tutorial/preprocessing/ (which is the first tutorial to use this code).

**Comment by aranas** [comment]
Okay I will create a pull request implementing this change

**Comment by schoffelen** [comment]
I think that this can be closed, no? Please reopen @matsvanes if this was incorrect.
