### ISSUE TITLE
Reading in all conditions at once in tutorial on Trigger-based trial selection

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/website#201]
Instead of epoching and preprocessing the data seperately for each condition, do it once for all data (as is usually done). 
Note that all other tutorials rely on this data. In order to ensure that these still work, conditions should be seperated using ft_selectdata before saving the data. @aranas @yingjoeyzhou

**Comment by matsvanes** [comment]
I've now changed this (not issued a pull request yet), but I see two discussion points:

1. The default trial function and the manually written trial function (mytrialfun) now give the exact same results. This does not show what the benefit is of using a user specified trial function. Is there anything we could change (like variable trial duration, response button, extra information in the trl structure)?

2. In this tutorial there is a reference to the tutorial on visual artifact rejection. I propose to change this to the tutorial on semi-automatic artifact rejection as I think that this is more commonly used (especially for large datasets).

**Comment by robertoostenveld** [comment]
perhaps we could make the `mytrialfun` a bit more interesting by including a `prevtrigger` column (with NaN for the very first trial). There are no responses in this data, so your other suggestions don't really suit this data.

**Comment by robertoostenveld** [comment]
Re your 2. 

The `PreprocData.mat` is used directly in http://www.fieldtriptoolbox.org/tutorial/visual_artifact_rejection/ I think it is a useful tutorial. The semiautomatic artifact rejection works well for data where all channels (plus noise) are rather similar, but not if channels have different patterns (e.g. as with EEG, but also neuromag). 

I propose to keep it as it is.

**Comment by robertoostenveld** [comment]
The http://www.fieldtriptoolbox.org/tutorial/automatic_artifact_rejection/ and the http://www.fieldtriptoolbox.org/tutorial/visual_artifact_rejection/ should both get a section "suggested further reading" for both pointing back to the http://www.fieldtriptoolbox.org/tutorial/artifacts/, and each of them pointing to the other.

**Comment by matsvanes** [comment]
I've implemented the suggested changes
https://github.com/fieldtrip/website/pull/202

**Comment by matsvanes** [comment]
Note that PreprocData has not yet been updated on the ftp server. Please inform me about procedure for updating this @robertoostenveld

**Comment by robertoostenveld** [comment]
for reference, PreprocData has been updated.
