### ISSUE TITLE
document the requirements for ft_specest_irasa

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#205]
See https://github.com/fieldtrip/fieldtrip/issues/1316

**Comment by robertoostenveld** [comment]
@StolkArjen can you do this?

**Comment by StolkArjen** [comment]
Sure, added to the list..

**Comment by StolkArjen** [comment]
Oh, I see, there's ft_specest_irasa (obviously) and the respective test function which does more than calling ft_specest_irasa. Namely, it generates pink noise and fits curves to powerspectra resulting from the IRASA procedure. ft_specest_irasa itself would not require more than its sisters, including ft_specest_mttmfft. So the steep dependencies, on a myriad toolboxes, concern the test function only. Hence I will add ft_specest_irasa to where it mentions the other specest functions on the requirement page.

**Comment by StolkArjen** [comment]
Except, where can one find "/shared/faq/requirements.md"? faq/requirements.md is pointing to it (-self?)

**Comment by schoffelen** [comment]
it's in _includes/shared/faq

**Comment by schoffelen** [comment]
Do you need anything more to finish and close this @StolkArjen ?

**Comment by StolkArjen** [comment]
I remember doing this already directly on the wiki, so yes go ahead and
close it.

**Comment by schoffelen** [comment]
uhm, you can close yourself, right? For now I will do this for you :)

**Comment by StolkArjen** [comment]
that would require a dramatic shift in my conceptualization of github

**Comment by StolkArjen** [comment]
btw, this reminds me that some figures need adding still on
http://www.fieldtriptoolbox.org/example/irasa/

in which folder of my ft website git repo should these figures go? - sorry,
I'm a little rusty

**Comment by schoffelen** [comment]
I thought so. Will I see you at bootcamp later?

**Comment by StolkArjen** [comment]
sorry, no, barely speak matlab anymore (javascript, don't ask)

can I create assets/img/example/irasa/ ?

**Comment by schoffelen** [comment]
but you still speak burpee, right?

sure you can create this, but it would require some git magic :)

**Comment by StolkArjen** [comment]
which bootcamp are you referring to?:)
