### ISSUE TITLE
remove integration with facebook

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#211]
We have not been using FaceBook actively over the last few years. I don't see the point in still spilling information from all visitors to the fieldtriptoolbox.org website to FaceBook. 

Hence I propose to remove the FaceBook integration.

@Spaak what do you think?

**Comment by Spaak** [comment]
I propose to leave the include file for now (just don't include it anymore), it might come in handy at some point.

**Comment by robertoostenveld** [comment]
fine, thanks!
