### ISSUE TITLE
Link to data in dipole fitting example broken

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#219]
@britta-wstnr reported in https://github.com/fieldtrip/fieldtrip/issues/1338

I lately wanted to check out something in this tutorial:
http://www.fieldtriptoolbox.org/workshop/natmeg/dipolefitting/

and noticed that the link to dicom.zip does not exist on the FTP server anymore (the folder it links to is not there: server-address/workshop/natmeg/dicom.zip ).

I know the example is from a quite old workshop but I wonder if it can be fixed/if the data just got moved and is still on the server, so could be re-linked.

**Comment by britta-wstnr** [comment]
Ah, my bad for reporting in the wrong place, thanks @robertoostenveld !

**Comment by robertoostenveld** [comment]
no worries. I am just looking whether I can find them again.

**Comment by robertoostenveld** [comment]
yes, they are under `server-address/tutorial/natmeg`. I now do indeed recall that there was some confusion as to this being documented under `tutorial` or `workshop` on the website (and hence ftp)

**Comment by robertoostenveld** [comment]
I have moved the data `tutorial/natmeg` over to `workshop/natmeg`. It can take up to 60 minutes before it synchronizes with the actual ftp server. For now you should be able to download it from the old location (simply start at `/pub/fieldtrip`). I'll keep the bug open and check at a later time that the affected links from the website work again.

**Comment by britta-wstnr** [comment]
Awesome, thanks @robertoostenveld !

**Comment by britta-wstnr** [comment]
Also, reporting that the link in the tutorial works now!

**Comment by robertoostenveld** [comment]
thanks
