### ISSUE TITLE
work through all FAQs on the website and check whether they need updates 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#222]
Discussed this with @yingjoeyzhou in a Zoom meeting: I have an alphabetical todo list of all FAQs that need to be looked at for formatting and internal consistency. I will put this online as a google sheet to facilitate working on this jointly.

**Comment by robertoostenveld** [comment]
See https://docs.google.com/spreadsheets/d/1xE8at6Ac-VMTYOmEogmp9ya_HtVcPI5aITKJr6MXAw8/edit?usp=sharing

Things to check for
- Is the title consistent (on the page as H1, in the header of the page, in the FAQ overview) 
- Is the formatting consistent (see also http://www.fieldtriptoolbox.org/development/guideline/website/ and https://github.com/fieldtrip/website/blob/master/README.md#house-prose-style)
- typo's or grammatical errors
- correct line endings (lines that ended with a ":" have often been truncated when transferring to the new wiki, and the last character is missing. E.g. "For example:" would become "For exampl"
- are the tags consistent? Tags that happen only once are not useful, tags that happen too often are also not useful. 
- is the content up to date? 

When it is hard to decide, please flag the specific FAQ as such and pass it on to me or @schoffelen

**Comment by robertoostenveld** [comment]
@yingjoeyzhou  if you work on this, please make a branch for the proposed changed, make the changes, push it to your repo, and send a PR. That branch would contain all changes of say one day of work. Reviewing and merging is quick, so the next day you would go back to your master branch, checkout the merged changes and again make a new branch with the proposed changes. 

So don't make a branch for each individual FAQ, but rather for a batch of FAQs that you do in one day.  Also, don't wait longer than a day in pushing and merging.

**Comment by yingjoeyzhou** [comment]
Ok I get it now. I'll try and work on it either tomorrow or Friday. If
things go wrong then please let me know :)

**Comment by robertoostenveld** [comment]
@elie-rassi FYI, Joey is going to pick this up. Perhaps you want to continue with this as well? I have now posted a google sheet with all FAQs so that it is easier to keep track of which ones have been done.

**Comment by yingjoeyzhou** [comment]
Cannot decide if the "old and difficult way" is still useful. Yet it was quite obvious that there's a formatting problem (maybe because of failure displaying images) in that section. @robertoostenveld would you take a look? http://www.fieldtriptoolbox.org/faq/how_can_i_convert_an_anatomical_mri_from_dicom_into_ctf_format/

**Comment by yingjoeyzhou** [comment]
this short faq http://www.fieldtriptoolbox.org/faq/how_can_i_define_my_own_neighbourhood_template/
can be "merged" into the longer one http://www.fieldtriptoolbox.org/faq/how_can_i_define_neighbouring_sensors/ to avoid switching cost of the reader. 

Shall i simply copy-paste contents from the short one to the long one, and archive the short one?

**Comment by schoffelen** [comment]
closing this because @yingjoeyzhou has resigned from contributing to fieldtrip
