### ISSUE TITLE
Fix error in tutorial on using simulated ERPs to explore cluster statistics

### ISSUE THREAD

**Issue by thor4** [fieldtrip/website#226]
After creating the timelock variables, the following code throws an error:
`cfg = [];`
`cfg.operation = 'x1-x2';`
`cfg.parameter = 'avg';`
`difference = ft_math(cfg, timelock1, timelock2);`
`Error using ft_math (line 144)
the requested parameter is not present in the data`

This can be fixed by commenting out the .keeptrials from the previous section:
`cfg = [];`
`% cfg.keeptrials = 'yes';`

However, this section with the `ft_timelockanalysis` function must be re-run with .keeptrials uncommented to get the trial data back into the timelock structs so that the section with `ft_timelockstatistics` near the end works.

**Comment by robertoostenveld** [comment]
The example on http://www.fieldtriptoolbox.org/example/use_simulated_erps_to_explore_cluster_statistics/ seems to predate some changes that we made to ft_timelockanalysis. The function used to always compute the average, so with keeptrials=yes, it would return `avg` and `trial`, and with keeptrials=no it would only return `avg`. However, we found that for some FT functions that would happen later in the pipeline (like ft_selectdata and ft_multiplotER) it was confusing if both were present. E.g. if you first make a selection of trials and then plot, should the plotting function recompute the average (on selected) or use the (outdated) average.

**Comment by robertoostenveld** [comment]
The behaviour is now that ft_timelockanalysis returns `avg` when keeptrials=no, and `trial` when it is yes. The example still assumes it returns both.

**Comment by robertoostenveld** [comment]
executing the code, I now see that ft_singleplotER is doing the averaging on the fly (as expected). So changing it into 

```cfg = [];
cfg.operation = 'x1-x2';
cfg.parameter = 'trial'; % CHANGE THIS
difference = ft_math(cfg, timelock1, timelock2);
```
computes the difference,  and 

```
figure
cfg = [];
ft_singleplotER(cfg, difference);
legend({'difference'})
```

then plots it. However, this is the trial-by-trial difference. I.e. firs the difference is computed between all trials in condition1 and condition2, and then that difference is averaged. That is fine if the data is paired and has teh same number of trials. But if the data is not paired over conditions (e.g. trial 1 in condition 1 corresponding to trial 1 in condition2), and if the number of trials is different, ft_math will give an error. 

Given the example, it is better to compute the condition-specific average first, then take the difference, and then plot. 

I will change the code.

**Comment by robertoostenveld** [comment]
The updated version should be online in a few minutes. Thanks for reporting!

**Comment by thor4** [comment]
Thanks for such a quick and informative response!
