### ISSUE TITLE
The formatting of the head movement example is messed up

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#232]
See http://www.fieldtriptoolbox.org/example/how_to_incorporate_head_movements_in_meg_analysis/

**Comment by StolkArjen** [comment]
See https://github.com/fieldtrip/website/pull/235 for a proposed fix

**Comment by schoffelen** [comment]
thanks, let's see how it renders.

**Comment by StolkArjen** [comment]
Thanks, this worked out fine
