### ISSUE TITLE
document the spm8/spm12 path better, to deal with mex file problems 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#236]
I suggest to rename http://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path

into "how to setup my fieldtrip path" and add the spm8/spm12 there as well

**Comment by schoffelen** [comment]
I can do this, but just to be sure: should I also rename the *.md file? I guess that this would break any bookmarks, right? On the other hand, for clarity it would make sense to do so @robertoostenveld.

**Comment by schoffelen** [comment]
This has been done.
