### ISSUE TITLE
merge FAQs on neighbors

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#246]
this short faq http://www.fieldtriptoolbox.org/faq/how_can_i_define_my_own_neighbourhood_template/
can be "merged" into the longer one http://www.fieldtriptoolbox.org/faq/how_can_i_define_neighbouring_sensors/ to avoid switching cost of the reader. 

Shall i simply copy-paste contents from the short one to the long one, and archive the short one?

_Originally posted by @yingjoeyzhou in https://github.com/fieldtrip/website/issues/222#issuecomment-629767274_

**Comment by robertoostenveld** [comment]
Yes, please go ahead and merge the two. the short one should be deleted (also from the `faq.md` overview page)To ensure that existing links (e.g. in emails etc) do not break, please add a `redirect_from` entry at the top. 

You can find an example in https://raw.githubusercontent.com/fieldtrip/website/master/support.md and you can check on http://www.fieldtriptoolbox.org/community/ that it works.

The one that remains (i.e. `/faq/how_can_i_define_neighbouring_sensors`  should have the redirect entry, and specify that the old one `/faq/how_can_i_define_my_own_neighbourhood_template/` is to be redirected to the remaining one.

**Comment by schoffelen** [comment]
BTW, I haven't removed the to-be-unlinked short faq

**Comment by schoffelen** [comment]
So, do I need to add a redirect_to on the old page, or, if I remove it altogether, it should work

**Comment by robertoostenveld** [comment]
The `redirect_to` goes in the new page, referring to the old page, and the old page is to be deleted.

I checked both links (from the first post) and both redirect to the same page. So the old page can be deleted. I'll do that now.
