### ISSUE TITLE
A mistake in getting_started/eeglab/

### ISSUE THREAD

**Issue by elvisjade** [fieldtrip/website#247]
I find a mistake in this webs：
http://www.fieldtriptoolbox.org/getting_started/eeglab/
https://github.com/fieldtrip/website/blob/master/getting_started/eeglab.md

Together with the EEGLAB developers we maintain two functions for converting the data back and forth: fieldtrip2eeglab and eeglab2fieldtrip. Please note that eeglab2fieldtrip is included in the FieldTrip release, and that fieldtrip2eeglab is included in the EEGLAB release.

It seems  eeglab2fieldtrip is included in the EEGLAB release.

**Comment by robertoostenveld** [comment]
You are right, both are now maintained in the EEGLAB repository.

**Comment by robertoostenveld** [comment]
I have fixed it on the website and now added both to the `fieldtrip/external/eeglab` directory in the fieldtrip repository.

**Comment by elvisjade** [comment]
> I have fixed it on the website and now added both to the `fieldtrip/external/eeglab` directory in the fieldtrip repository.

Can you provide a more clear or easy to understand data import tutorial? At present, some tutorials do not seem to be very easy to use.

I am a user of mne and eeglab, and I am studying fieldtrip recently. I have been reading the official tutorial for a long time and still do n’t understand how to import my own egi （.raw）data and eeglab data. I used eeglab2fieldtri and just imported one, but it was imported when eeglab opened certain data. I still don't know how to directly import the data.


（http://www.fieldtriptoolbox.org/faq/how_can_i_import_my_own_dataformat/
http://www.fieldtriptoolbox.org/reading_data/）

**Comment by robertoostenveld** [comment]
as we write on the getting started 

> In general you should get started with the tutorials. The pages that are listed below only serve to explain system specific details and peculiarities, but lack the complete overview that the tutorials provide.

I propose you follow this [tutorial](http://www.fieldtriptoolbox.org/tutorial/continuous/#reading-continuous-eeg-data-into-memory), which is 3 lines in a MATLAB script. It does not get simpler than that. 

If your question is more specific, then I suggest you ask it on the [mailing list](http://www.fieldtriptoolbox.org/discussion_list/), where many people can help you with preprocessing of EEG data (either EGI or other formats, and either starting from the native raw format or from EEGLAB).

**Comment by elvisjade** [comment]
> as we write on the getting started
> 
> > In general you should get started with the tutorials. The pages that are listed below only serve to explain system specific details and peculiarities, but lack the complete overview that the tutorials provide.
> 
> I propose you follow this [tutorial](http://www.fieldtriptoolbox.org/tutorial/continuous/#reading-continuous-eeg-data-into-memory), which is 3 lines in a MATLAB script. It does not get simpler than that.
> 
> If your question is more specific, then I suggest you ask it on the [mailing list](http://www.fieldtriptoolbox.org/discussion_list/), where many people can help you with preprocessing of EEG data (either EGI or other formats, and either starting from the native raw format or from EEGLAB).

Thanks for your reply! I will try this tutorial.
