### ISSUE TITLE
tutorial data on ftp inconsistent with data extracted in current tutorials

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/website#252]
This is a potentially serious issue with wide ramifications: working on #203 I cleaned up the test code of test_tutorial_clusterpermutationtimelock, to reflect the latest state of the code as reflected on the website. This included the change from the per-condition preprocessing, to a three-condition preprocessing only then followed by a condition split (as per the shared sections of documentation definetrial_all.md and preprocessing_lp.md). As it turns out, for the clusterpermutation_timelock tutorial at least, the single condition data dataFC_LP and dataFIC_LP which are extracted  this way, both have different numbers of trials as compared to the data that is stored on the ftp (of which the latest version dates from 2014 or so). Although the number of trials is not that shocking (on the order of ~2), it has a substantial impact on the numbers that come out of the subsequent statistical evaluation step. 
Replacing the old data with the new would require the generation of new figures (+results in the fact that the p-values and clusterstats are much less 'extreme' than before), and probably has ramifications to all tutorials that use the same replaced shared code for the preprocessing etc. @aranas @matsvanes @yingjoeyzhou have you encountered something like this when working on the tutorials earlier this year? Also, in updating the tutorial pages, have you also 

1) updated the test_tutorial_<tutorial> scripts and 
2) ran the test_tutorial_<tutorialname> scripts and
3)  saved the intermediate data to /home/common/.../ftp and
4) updated the figures?

I guess that this pertains to basically all the 'basic' tutorials' that are typically used in the toolkit:
-eventrelatedaveraging
-freqanalysis
-beamforming

(I am currently working on the clusterpermutationtimelock tutorial, because that apparently was not finished)

I think that the easiest solution would be to try and find out whether  the list of 'bad trials' somehow went wrong in the new versus the old implementation, and adjust that at the level of the shared definetrial_all section. This will be relatively painfree, provided you haven't updated the data/text/figures in the meantime.

**Comment by schoffelen** [comment]
The plot thickens: 

The eventrelatedaveraging tutorial shows this snippet of code:

<img width="824" alt="Screenshot 2020-06-12 at 11 53 05" src="https://user-images.githubusercontent.com/1517611/84490388-64434b80-aca3-11ea-8986-bba1df9c051b.png">

**Comment by schoffelen** [comment]
But also this snippet of code (notice the commented trigger values correpsonding to the individual conditions: 

<img width="736" alt="Screenshot 2020-06-12 at 11 54 39" src="https://user-images.githubusercontent.com/1517611/84490484-86d56480-aca3-11ea-9da5-3bc9b6aca217.png">

**Comment by robertoostenveld** [comment]
hmm, the trigger codes don't match.

**Comment by schoffelen** [comment]
So, either the redefinetrial swapped the IC and FC triggers, or the documentation is incorrect.

If I look at that test_tutorial_eventrelatedaveraging, which still seems to reflect the old way of doing things, the FC trigger corresponds to a '9', thus the ft_redefinetrial step is going wrong.

I will now investigate whether this causes the above described inconsistency.

**Comment by schoffelen** [comment]
what a mess.

**Comment by schoffelen** [comment]
OK, confirmed. The 5 and 9 should be swapped in the ft_redefinetrial section. This essentially cased the 'dataIC' and 'dataFC' to be swapped. Doing this by hand and computing the stat (FIC vs. FC) now yields a clusterstat that is getting close to the one reported on the website. Yet, there is still one more 'bad trial' in the data_all, in comparison to the combined bad trials for the originally extracted dataFC etc. Does anybody have an idea where this comes from? @aranas @yingjoeyzhou @matsvanes

**Comment by schoffelen** [comment]
To do:

- [ ] swap the 5 and 9 trigger codes in the respective ft_redefinetrial sections
- [ ] get feedback from @aranas, @matsvanes, @yingjoeyzhou whether they recently updated any tutorial figures (after the shared definetrial_all went live)
- [ ] decide whether the badtrial definition new-style should be forced to be exactly equal to how it was before, to maximize the probability that the individual condition data comes out identical
- [ ] check the consistency of the data on the ftp, both with respect to the recipe in the tutorials, and with respect to each other: eventrelatedaveraging, clusterpermutation_timelock, freq, beam, and possibly others.

**Comment by schoffelen** [comment]
I took the executive decision to force the list of badtrials (as defined in the shared preprocessing_lp.md etc.) to be a match to how it was defined before, this required to remove trial 132 from the list of bad trials. As a result, the reported stat.posclusters(1).clusterstat is consistent again with the one that results from the computations using the currently advertised aanvliegroute.

**Comment by schoffelen** [comment]
Self answering one of the questions posed above: it seems that @matsvanes has re-created the ftp data in preparation for the toolkit (march 2020). Since a quick comparison on /home/common/matlab/fieldtrip/data/ft/tutorial yields 3 dataFIC_LP.mat (and FC) files that are quite different in size, and given the mix up with the trigger codes, I suspect that the numeric content of these 3 files might very likely be different relative to one another, unfortunately

**Comment by schoffelen** [comment]
BTW the other tutorials that have a precomputed dataFC etc are the minimumnormestimate and cluster_permutation_timelock

**Comment by schoffelen** [comment]
I checked the consistency of the data on ftp, and it is now clear that the conditions are wrong in the eventrelatedaveraging tutorial: IC and FC should be swapped (and in addition one trial should not have been removed).

**Comment by schoffelen** [comment]
For now I will physically swap the file names, but we should fix this in the code of test_tutorial_blabla, and run the function once with the save options uncommented

**Comment by schoffelen** [comment]
swapping of file names was not good. I have now updated the test_tutorial code and ran a full sweep. new data has been saved to the ftp.
