### ISSUE TITLE
headmodel tutorial error

### ISSUE THREAD

**Issue by kenzo0619** [fieldtrip/website#261]
Hi expert, I am new to Fieldtrip and I'm trying to learn how to create a head model, but it gets me an error when I try to align electrodes to head model. The Matlab error shows: 
**Error in ft_electroderealign (line 480)
tmpl_nas(i,:) = target(i).elecpos(nas_indx,:);** 
I am using Matlab 2019a and the newest fieldtrip version. I have also tried the older version but the error is the same. May I ask your help with this?
The web of tutorial is 👍 http://www.fieldtriptoolbox.org/tutorial/headmodel_eeg_fem/

**Comment by schoffelen** [comment]
You may ask for help, but this is not the right location. Please refer to the e-mail discussion list to ask for help, and take care to put sufficient information in you e-mail. The stuff you wrote above is not sufficiently informative.
