### ISSUE TITLE
Add a link to the online lectures of Mike  X Cohen

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#366]
@mikexcohen has a series of lectures on youtube that we should link to on https://www.fieldtriptoolbox.org/video/#other-online-video-resources

**Comment by complexbrains** [comment]
Hi Robert, 

it is one of the lecture series I learnt all the basics that I know about the analysis of EEG data. So it is a pleasure to fix this issue! 
Thank you!
