### ISSUE TITLE
Mistake in the example for the realtime signal viewer

### ISSUE THREAD

**Issue by Yodaswag** [fieldtrip/website#405]
the following relates to code presented in the fieldtrip documentation (in this link):
https://www.fieldtriptoolbox.org/example/ft_realtime_signalviewer/#example-use

____________________________________________________________________________________________
running:
```
cfg                = [];
cfg.channel        = 1:10;                         % list with channel "names"
cfg.blocksize      = 1;                            % seconds
cfg.fsample        = 250;                          % sampling frequency
cfg.target.dataset = 'buffer://localhost:1972';    % where to write the data
ft_realtime_signalproxy(cfg)
```
will return the following error:
```
Unrecognized function or variable 'B'.

Error in ft_realtime_signalproxy (line 117)
  FM = ft_preproc_online_filter_init(B, A, zeros(hdr.nChans, 1));
```

this is because the variable B is created only when a filter is added to the cfg struct.

for example, this code will work fine:
```
cfg                = [];
cfg.channel        = 1:10;                         % list with channel "names"
cfg.blocksize      = 1;                            % seconds
cfg.fsample        = 250;                          % sampling frequency
cfg.target.dataset = 'buffer://localhost:1972';    % where to write the data
cfg.lpfilter = 'yes';
cfg.lpfreq = 1;
ft_realtime_signalproxy(cfg)
```

**Comment by robertoostenveld** [comment]
thanks for reporting, you are right.  The documentation on the website and the actual code are not consistent. However, I think it would be better to fix it in the code instead. There is now the option `cfg.onlinefilter` which is not documented, and for which the default ('yes') is not linked to the actual setting of the lpfilter/hpfilter/bpfilter.

I don't understand what the purpose of `cfg.onlinefilter` is and will remove it from the code ...

**Comment by robertoostenveld** [comment]
if you download the latest master, or wait until the next release (probably tonight), the code will be fixed.
thanks once more!

**Comment by robertoostenveld** [comment]
Now that I look at the documentation, I notice that it has not been updated for quite some time and some URL links are broken. The functions that are listed on the documentation pages are now also in the fieldtrip release, so better would be not to list them on the website pages any more, as that only makes maintenance harder.
