### ISSUE TITLE
Can't read Artinis oxy4 file in real-time

### ISSUE THREAD

**Issue by Yodaswag** [fieldtrip/website#407]
I am currently trying to read to data from my Artinis Octamon directly into Matlab in real-time using the fieldtrip buffer.
This is the code I ran:
```
cfg                = [];
cfg.channel        = 1:8;                         % list with channel "names"
cfg.blocksize      = 1;                            % seconds
cfg.fsample        = 10;                          % sampling frequency
cfg.nRx = 2;
cfg.target.dataset = 'buffer://localhost:1972';    % where to write the data
cfg.lpfilter = 'yes';
cfg.lpfreq = 1;
cfg.export.dataformat = 'matlab';
cfg.export.dataset = 'C:\Users\NIRS\Documents\Filepath\OxysoftData.mat';
cfg.dataset = 'C:\Users\NIRS\Documents\Filepath\OxysoftData.oxy4';
ft_realtime_signalrecorder(cfg);
```

and this is the error that I keep getting if I run it while recording new data in Oxysoft:
```
Reference to non-existent field 'nRx'.

Error in read_oxy4_header

Error in read_artinis_oxy4 (line 65)
  data = read_oxy4_header(filename);

Error in ft_read_header (line 2432)
    hdr = read_artinis_oxy4(filename);

Error in ft_realtime_signalrecorder (line 72)
hdr = ft_read_header(cfg.headerfile, 'headerformat', cfg.headerformat, 'cache', true, 'retry',
true);

```
When running the same code after finishing the recording I don't get an error and instead I get this:
`processing segment 1 from sample 2900 to 2909 ` - Number of samples processed changes between files.

In addition, the OxysoftData.mat file appears as it should with the few samples that have been processed appearing for each of the channels.
_________________________________________________________________________________________________________

I noticed that a .tmp file appears while the recording is active and I tried to copy that, change its name to OxysoftData2.oxy4 and then run the same code from above only with a different dataset and I get this error:

```
Error using readoxy4file
[Artinis] 404 - File not valid!

Error in readoxy4file

Error in read_oxy4_header

Error in read_artinis_oxy4 (line 65)
  data = read_oxy4_header(filename);

Error in ft_read_header (line 2432)
    hdr = read_artinis_oxy4(filename);

Error in ft_realtime_signalrecorder (line 72)
hdr = ft_read_header(cfg.headerfile, 'headerformat', cfg.headerformat, 'cache', true, 'retry',
true);
```

**Comment by robertoostenveld** [comment]
Hi @Yodaswag, 

the Artinis code is not fully open-source (some functions are precompiled p-files) and is not maintained by the core FieldTrip team. You should therefore ask for support at Artinis, e.g. @Horschig or @sofisappia. 

Furthermore, issues with the code (like this) should be reported at the `fieldtrip/fieldtrip` repository, not the `fieldtrip/website` repository.

**Comment by Yodaswag** [comment]
I see. Thank you very much for your help and support robert

Kind regards, Ori Shriki

P.s  my father, Oren Shriki, Send his regards as well :)
