### ISSUE TITLE
BIDS example image is broken

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#456]
I don't know what happened, but the image `assets/img/example/bids/BIDS_example.png` is broken. This is on the website, on github, and also on my local computer.

@LucaLaFisca could you check your copy?

**Comment by robertoostenveld** [comment]
the image itself. This is what I get 

![Screenshot 2021-09-16 at 16 50 17](https://user-images.githubusercontent.com/899043/133634287-b25e2c53-b122-4acd-982e-101b6488a369.png)

and this

![image](https://user-images.githubusercontent.com/899043/133634521-48c2ca2c-d2cb-45f1-9eb4-6922b3e92169.png)

The clone/copy on my own computer also has an image that does not work. Or is it due to my computer? If you go to https://www.fieldtriptoolbox.org/example/bids/, do you see the image?

**Comment by LucaLaFisca** [comment]
That's weird... I just went to the github page with the account of a colleague and the image appears properly.
Yes, I see the image when I go to the website:
![image](https://user-images.githubusercontent.com/39408466/133636291-600bfc98-878a-4940-8488-1eea78ccf2ab.png)

**Comment by robertoostenveld** [comment]
hmm ... I just tried with different browsers, the problem only applies to Safari, Firefox and Chrome are both fine.

**
![image](https://user-images.githubusercontent.com/899043/133637339-153e2b2b-5e3f-4f99-91dc-f42f0e5f8861.png)
**

So it is specific to my computer.

**Comment by LucaLaFisca** [comment]
Ok... Is it the same for the other images?

**Comment by robertoostenveld** [comment]
I established that the problem is due to the imagine being in [webp format](https://en.wikipedia.org/wiki/WebP) and not png as suggested by its extension. macOS Safari browsers only support webp in recent versions, apparently my version is too old. 

@LucaLaFisca can you convert the webp file to png?
