### ISSUE TITLE
headmodel_eeg_fem tutorial is broken.

### ISSUE THREAD

**Issue by schoffelen** [fieldtrip/website#480]
Based on the below e-mail on the discussion list, I wanted to look into the headmodel_eeg_fem tutorial.

I markdown2matlabbed it, but the code is dysfunctional. Several things seem amiss, e.g. the 'fid' structure that is created causes problems in electroderealign, and the 'style', 'sr' key-value pair is not supported for ft_plot_sens.

By consequence I have not yet gotten to the reported 'issue' yet. 

To do: 
- fix the tutorial on the website so that it runs through with the current code
- also check the relevant example script (where the leadfields are computed).
- look into the reported issue and report back to the reporter.

pinging @mcpiastra 

=========================================================

Dear all,
 
Recently, I came across something peculiar regarding the Leadfield matrix and the transfer matrix of the conduction volume model, created after following the Fieldtrip-SimBio pipeline.
 
The Leadfield matrix (from now on called LF) that is produced (which is a field inside the leadfield struct created from the ft_prepare_leadfield function) is a {1 x N_s} cell array, where N_s is the number of sourcepoints specified during the creation of sourcemodel. Assuming that all the source points are “inside” the brain (i.e. the “inside” field of the leadfield struct would be a column  {N_s x 1} full of ones), then LF contains N_s  cells, each one being of size {N_ch × 3 double}, where N_ch is the number of channels/electrodes used.
 
I noticed that the first row of each of these cells from the LF (i.e. for the first channel/electrode) for each of the source points is zero. This is obviously due to the transfer matrix, of which the first row is also comprised of zeros, and is created with the sb_transfer.m function. In this function, the creation of the transfer matrix clearly starts from the second in order channel/electrode (the for loop starts from the second channel).
 
Is there a reason for this? Shouldn’t it start from the first channel?
Thank you in advance.
 
Sincerely,
Zorzos Yiannis

**Comment by mcpiastra** [comment]
I am not familiar with this bit:
*I markdown2matlabbed it, but the code is dysfunctional. Several things seem amiss, e.g. the 'fid' structure that is created causes problems in electroderealign, and the 'style', 'sr' key-value pair is not supported for ft_plot_sens.*
but happy to work on the headmodel_eeg_fem tutorial.
@schoffelen we could discuss this during the next hackathon..?

best,
MC

**Comment by schoffelen** [comment]
I see. markdown2matlab converts the documentation file into a matlab script, so that it can be easily run in matlab.
There are some issues currently, which I will address first. Happy to discuss this further if needed.

**Comment by schoffelen** [comment]
I think it is now fixed, and it should work with the PR: https://github.com/fieldtrip/fieldtrip/pull/1919
