### ISSUE TITLE
remove ft_qualitycheck from the website

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#483]
linked to https://github.com/fieldtrip/fieldtrip/pull/1925 we should also clean up the documentation.

We have a FAQ on [how can I check the quality of an EEG or MEG recording](https://www.fieldtriptoolbox.org/faq/how_can_i_check_the_quality_of_an_meeg_dataset/) (which still mentions Odin). The content of the FAQ should move to https://github.com/Donders-Institute/meg_quality 

There is a short mention on the FAQ on [how to incorporate head movements in MEG analysis](https://www.fieldtriptoolbox.org/example/how_to_incorporate_head_movements_in_meg_analysis/)

There is a [reference page](https://www.fieldtriptoolbox.org/reference/ft_qualitycheck/), which will not be recreated, but the old page will also not be removed automatically. Hence it should be removed manually.

The cfg options are mentioned in the [index of all configuration options](https://www.fieldtriptoolbox.org/reference/configuration/), those should disappear automatically.

**Comment by schoffelen** [comment]
Good one. W.r.t. the FAQ that mentions Odin, given that it is specific to DCCN, should we consider moving it to the meg_quality github in some form?

**Comment by robertoostenveld** [comment]
yes, I don't think that one is of relevance for anyone outside the DCCN.
