### ISSUE TITLE
switch from FTP to WEBDAV for downloads

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#532]
FTP is getting more and more problematic, because webbrowsers don't support it any more, and because the RU ICT department considers it an unsafe protocol. 

The DCCN TG with @hurngchunlee are currently setting up a WEBDAV server to host the same files as now distributed via the FTP server. The name will be `download.fieldtriptoolbox.org` and it should become available both through http and https. For downloading single files, any webbrowser should do fine. For downloading a whole directory at once (e.g., for a workshop or the BIDS examples) a webdav client such as CyberDuck is recommended.

We have to make the corresponding updates to the website:

- [x] the PHP download form needs an update
- [x] search and replace the FTP server on all web pages
- [x] the "having download problems?" FAQ should be updated. 
- [x] the README.txt on /home/common/matlab/fieldtrip/data/ftp should be updated

**Comment by hurngchunlee** [comment]
The webdav (https://download.fieldtriptoolbox.org) is up and running.  Please test it and let me know if there are issues.

Furthermore, I would like to add one more item to the action list:
- [ ] inform the TG to decommission the FTP server

**Comment by robertoostenveld** [comment]
I have made the corresponding changes to the fieldtrip website, to the README and to the php download form. I suggest we wait a few days to see whether it all works as expected.

**Comment by robertoostenveld** [comment]
I have also added a news item on the front page. I decided not to add a tweet to it, it is not that interesting.

**Comment by hurngchunlee** [comment]
@robertoostenveld shall we decommission the FTP server or you want to wait a bit longer?

**Comment by hurngchunlee** [comment]
thanks @robertoostenveld. The TG will take care of it.
