### ISSUE TITLE
Replace ft_redefinetrial with ft_selectdata in tutorial/eventrelatedaveraging

### ISSUE THREAD

**Issue by johalgermissen** [fieldtrip/website#552]
In this tutorial (used as entry tutorial in the Donders MEG/EEG Toolkit 2022), under https://www.fieldtriptoolbox.org/tutorial/eventrelatedaveraging/#cleaning, `ft_redefinetrial` is used to select different subsets of trials and then save them.

`ft_redefinetrial` isn't particularly flexible in selecting subsets of the data; e.g. you can't use it to select channels or frequencies as required in later tutorials. Hence, introducing `ft_selectdata` might be more beneficial to students.

Wouldn't it be more useful to teach them to use `
dataFIC_LP = ft_selectdata(cfg, data_all);
`
etc.?

**Comment by robertoostenveld** [comment]
agreed, `ft_redefinetrial` is overly complex and not needed here.

**Comment by robertoostenveld** [comment]
this has been resolved with #553 and #554
