### ISSUE TITLE
add the material for the madrid2019 workshop

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#58]
as discussed with @dieloz and @aranas

**Comment by robertoostenveld** [comment]
The links are already present on the madrid2019 page, and placeholder pages are in place for the 4 hands-on sessions.  

- [ ] tutorial_erp
- [ ] tutorial_cleaning
- [ ] tutorial_freq
- [ ] tutorial_stats

Furthermore, we need the general 

- [ ] dataset description for `eeg-chennu`
- [ ] dataset description for `eeg-language`

These don't have to be elaborate. E.g. one paragraph plus pointers to relevant external publications. Including an image of stimulus material and timeline would be nice.

**Comment by dieloz** [comment]
@aranas Could you please take care of the dataset description thing? I'm still working on the tutorials

**Comment by robertoostenveld** [comment]
I have added two short dataset descriptions to the website. These will soon (in a few minutes) also be visible from http://www.fieldtriptoolbox.org/workshop/madrid2019/

**Comment by robertoostenveld** [comment]
There is now a draft version of tutorial_cleaning and tutorial_stats online. Please check them and make edits in the shared Dropbox. Idem for the dataset descriptions.

**Comment by robertoostenveld** [comment]
I will stop working on it for now.

**Comment by aranas** [comment]
great, thank you Robert! I am almost done with reworking the tutorial_cleaning, will let you know when all the files are in the dropbox

**Comment by dieloz** [comment]
Great Robert! Thanks a lot for the work. I just added a couple of blank lines in the "### Statistical Testing of the Relation Between a Neurobiological and a Behavioural Variable" section after points 1 and 2: the matlab code was text (no clue why this happens)

**Comment by aranas** [comment]
tutorial_cleaning is up and I will do the formatting of it tonight
@dieloz thanks for your script, the topos look indeed just as expected! I will change & extend the erp tutorial now and let you know when it is finished.
Also,  I just met with Robert and have some notes on structure and formatting of the tutorials, so once the freq_task and freq_resting tutorials are finished @dieloz can let me know and then I will merge them into one and take care of the headings

**Comment by dieloz** [comment]
Hi @aranas! thanks for letting me know. The freq tutorial is finished (figures and matlab code) I even converted to markdown and seems ok. I already paste task and resting data (sorry if I messed). You'll find images in Dropbox/Chennu2016PLoSBiol/tutorial/tutorial_freq

@robertoostenveld : to put the tutorial data in FTP what should we do? So far is in the dropbox, together witht he images which is inconvenient. Let me know

**Comment by aranas** [comment]
@dieloz great, I see that you merged them. It looks good! I will just do some formatting to it and then I can put it up on the website together with the images, Robert showed me how to do this.

**Comment by robertoostenveld** [comment]
The procedure for adding (or deleting) files to the FTP server is that they are copied (or deleted) on `/home/common/matlab/fieldtrip/data/ftp/workshop/madrid2019/` on our central storage. Every hour or so (under control by the TG) that whole ftp directory is synchronized with the FTP server itself. So I cannot directly access the FTP server, but can put the files in the right location. I gave @aranas the same right, she is also able (though an ssh tunnel) to do it remotely. 

I just uploaded the two mat files from tutorial_freq, it should appear on the FTP server soon.

**Comment by robertoostenveld** [comment]
Should I also upload `freq_resting.mat` from the `tutorial_stats` folder on Dropbox?

What about the .m files (plotSpread and sem)?

**Comment by dieloz** [comment]
Put them all. freq_resting.mat contains freq data from all participants and sessions and the other functions are needed to plot

**Comment by robertoostenveld** [comment]
done!

**Comment by robertoostenveld** [comment]
I had a lok at the freq tutorial: it is to long. I propose in the tar section to delete 2 of the 4 topics, only keep fixed length Hanning and Morlet. No multi and no variable timwin. Better have the participants spend more time on Resting state power spectra

**Comment by dieloz** [comment]
Sure. I keep multitapers for resting state isnt it? I'm commuting: in ~1h I make the pull request

**Comment by robertoostenveld** [comment]
Yes, keep dpss in last part

**Comment by robertoostenveld** [comment]
I have also added the bids conversion script

**Comment by dieloz** [comment]
It would be nice to share the pipelines to see what I've done in all subjects. In 

Dropbox\Chennu2016PLoSBiol\code\pipelines 

feel free to add step1* to step4* matlab scripts. They go from raw data to freq following the bids folder structure we agreed.
