### ISSUE TITLE
remove outdated DMLT multivariate analysis tutorial 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#594]
The external DMLT code has not been maintained and It was recently reported through the FT mailing list that the tutorial does not work any more. The original authors have even removed the code that was once upon a time shared on https://github.com/distrep/DMLT.  

I don't see the reason why we would keep this tutorial online, and also propose to remove the `external/dmlt` directory from the fieldtrip toolbox itself.

**Comment by schoffelen** [comment]
OK, this requires some changes to the website repo, and to the fieldtrip repo

for the website, I suggest to just unlink the tutorial on the tutorial table-of-contents page, and add an even stronger note to the top of the mvpa tutorial page, should anybody still end up there.

for the code repo I will remove the external/dmlt folder, move ft_statistics_crossvalidate to external/obsolete, update de docstrings in ft_timelock/freqstatistics, and adjust the relevant functions in the test-folder.

**Comment by robertoostenveld** [comment]
why not remove it altogether? If we keep it, then a google search might still direct to it. Or people might end up there 
by other means. If we don't want people to run that code, I think it is better to make it disappear altogether. People can still look it up (if they really care) in the github history.
