### ISSUE TITLE
git clone doesn't work since two files have the same name

### ISSUE THREAD

**Issue by contsili** [fieldtrip/website#684]
In Windows 10 command line and Git Bash while trying to clone my forked fieldtrip/website repository, I stepped into an error:

_C:\Users\user\Desktop>git clone https://github.com/contsili/website.git
Cloning into 'website'...
remote: Enumerating objects: 39469, done.
remote: Counting objects: 100% (917/917), done.
remote: Compressing objects: 100% (446/446), done.
remote: Total 39469 (delta 471), reused 908 (delta 464), pack-reused 38552
Receiving objects: 100% (39469/39469), 259.68 MiB | 6.17 MiB/s, done.
Resolving deltas: 100% (26952/26952), done.
error: invalid path 'tag/reproducescript?.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'_

I looked into the fieldtrip/website/tag/ repository and there are two markdown files that are saved twice with the same name: reproducescript.md and script.md. In the code preview in GitHub, it seems that one is saved as reproducescript.md and the other as reproducescript .md (with a space between the name and the file extension!). 

Windows (and Mac as far as I know) do not accept file names that include spaces between the name and the file extension. Hence, I believe that this is the reason why I can't clone my forked fieldtrip/website repository. I would suggest the names to be changed.

This issue is related with the commits: e383152c73160a76d7323f727db6b5d3310d4014 and de238ceda9b607769280666b28b57560b655f207.

**Comment by robertoostenveld** [comment]
These files under `tag` are automatically created (along with a corresponding yml file under `_data` and are based on the tags specified at the top of the actual website pages. Apparently upon initially creating there was a typo, causing the version with the space to be created. It is apparently not a problem on linux and macos (my platforms), but I can see it being a problem on windows. I will fix it.

**Comment by robertoostenveld** [comment]
there is actually not a space for the extension, but a carriage return (i.e. a `\r` or in ASCII a decimal 13).
