### ISSUE TITLE
images are missing

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/website#770]
@marlenemeyer reported that images are missing on https://www.fieldtriptoolbox.org/workshop/madrid2019/tutorial_freq/ (and possibly others). I can confirm.

In the readme we have a section on [checking for broken links and images](https://github.com/fieldtrip/website/blob/master/README.md#checking-for-broken-links-and-missing-images).

```
wget --spider -r -nd -nv -o spider.log http://localhost:4000
grep -B1 'broken link!' spider.log  | grep http > broken.log 
```

**Comment by robertoostenveld** [comment]
The missing image on the madrid2019 page is due to it referring to the `tfrtiles.png` image from another tutorial, and that being renamed over there. To prevent this from happening, tutorial and workshop pages should duplicate images, not reuse them from another page. Or alternatively, the images should explicitly be in the `assets/shared` directory.

**Comment by robertoostenveld** [comment]
@schoffelen I am fixing this now. Just for the future, some of them are in the recent coregistration_opm tutorial. Please note that references to online documentation on github should include the directory, so it should be for example `[ft_plot_sens]/reference/plotting/ft_plot_sens)` rather than `[ft_plot_sens]/reference/ft_plot_sens)`

**Comment by schoffelen** [comment]
OK, check.

**Comment by robertoostenveld** [comment]
I just pushed some updates, these images still need to be fixed:

```
https://www.fieldtriptoolbox.org/assets/img/getting_started/limo/hierarchical_analysis.png
https://www.fieldtriptoolbox.org/assets/img/template/layout/easycapm1.png
https://www.fieldtriptoolbox.org/assets/img/template/layout/4D148.lay.png
https://www.fieldtriptoolbox.org/assets/img/template/layout/4D248.lay.png
https://www.fieldtriptoolbox.org/assets/img/template/layout/4D248_helmet.mat.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/design.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/multipletrials.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/multiploter.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/multiploter_interactive.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/singleploter.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/topoploter.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/tfrtiles.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/multiplottfr.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/figurepipeline.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/sensor_analysis/analysispipeline_sensor_analysis.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/timefrequencyanalysis/tfrtiles.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/timefrequencyanalysis/tfr_pipelinenew.png
https://www.fieldtriptoolbox.org/assets/img/template/layout/easycapm10.png
https://www.fieldtriptoolbox.org/assets/img/tutorial/preprocessing_erp/example_eog.png
```

**Comment by robertoostenveld** [comment]
Along with the recent updates to the faq and example section in PR #812 and #825, I have tested for broken links and fixed a whole bunch of outdated figures. I believe that this is now fixed completely.
