### ISSUE TITLE
Updating recomendation for editor

### ISSUE THREAD

**Issue by JuliusWelzel** [fieldtrip/website#788]
Hi,

is there a current recommendation on what software to use since Atom has been [discontinued](https://github.blog/2022-06-08-sunsetting-atom/)?

https://github.com/fieldtrip/website/blob/c41285a67e506d541734427406d76b8fe74d3af4/example/bids_eeg.md?plain=1#L18

I recommend using [VSCode](https://code.visualstudio.com/).

**Comment by robertoostenveld** [comment]
Atom has not been discontinued, I use it on a daily basis. It is just not being further developed any more... But I agree that new people should not start using Atom. I'll change it to VSCode (which I also should start using more often).

**Comment by robertoostenveld** [comment]
Oh, the irony: I just used Atom to change the recommendation. 🙃
