### ISSUE TITLE
Old website had breadcrumbs - do we want to keep these?

### ISSUE THREAD

**Issue by Spaak** [fieldtrip/website#9]

**Comment by robertoostenveld** [comment]
it actually does not have breadcrumbs (we had those in the past), but a hierarchical representation of the current page that allows to quickly go back.

![screen shot 2018-11-01 at 12 57 43](https://user-images.githubusercontent.com/899043/47850522-c9e80a00-ddd5-11e8-9ef6-123b951ce854.png)

**Comment by robertoostenveld** [comment]
I think we should work on the hierarchy anyway, so lets close this specific issue for now.
